# Generated by Django 2.2.7 on 2019-11-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=1000, upload_to='', width_field=2000)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_desc', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSocialMediaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_desc', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('location', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField()),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='social_media.PostImage')),
                ('social_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_platform', to='social_media.SocialPlatform')),
            ],
        ),
    ]
