# Generated by Django 2.2.7 on 2019-12-08 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedPosts',
            fields=[
                ('projectpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content_management.ProjectPost')),
                ('deleted', models.BooleanField()),
            ],
            bases=('content_management.projectpost',),
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='images',
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='content_management.ProjectPost'),
            preserve_default=False,
        ),
    ]
